project:
  type: book

book:
  title: "Open and Reproducible Research"
  author: "Aditya Ranganath"
  date: "9/18/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: Cosmo
    toc: true 
    toc-depth: 3
    output-dire: docs 
  pdf:
    documentclass: scrreprt

editor: visual

